version: '3'

services:
  authjs:
    build:
      context: .
      dockerfile: Dockerfile
    image: authjs
    command: node auth.js
    volumes:
      - .:/home/authjs/app
      - /home/authjs/app/node_modules
    container_name: authjs
    restart: unless-stopped
    env_file: .env
    ports:
     - "5000:5000"
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    networks:
      - app-network
    
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    networks:
      - app-network
    env_file: .env
    environment: 
      DB: your_link:D
      SALT_SECRET: maybesalt:D
      WSPORT: ${PORT:-3000}

  webserver:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./dhparam:/etc/ssl/certs
    depends_on:
      - nodejs
      - authjs
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email diustilovsky@uc.cl --agree-tos --no-eff-email --staging -d grupo4arquichat.tk  -d www.grupo4arquichat.tk

volumes:
  certbot-etc:
  certbot-var:
  web-root:
  dhparam:

networks:
  app-network:
    driver: bridge